### ISSUE TITLE
Refactor the new scheduler

### ISSUE THREAD

**Issue by nkwangjun** [futurewei-cloud/global-resource-scheduler#102]
1、Unify the schedule object module
Currently there are two object module define， one is in the scheduler cache, such as node、stack、allocation，and they are defined in the scheduler cache,  there are some unused parameters in the module define, another is defined in the core/types, which is exposed in the API.

2、Supplementing Unit Test Cases
Two steps: First, new features for the scheduler must carry unit test cases. Second, we need to gradually supplement missing unit test cases for the initial scheduler code.

**Comment by nkwangjun** [comment]
#96 is contained in this code reflector issue

**Comment by nkwangjun** [comment]
implemented in #146

**Comment by nkwangjun** [comment]
We need to add more Unit Test Cases for the scheduler

**Comment by cathyhongzhang** [comment]
done
