### ISSUE TITLE
Implement distributor controllers & processes

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#113]
1. Build an independent distributor process which binds schedulers to pods.
2. For deleted pods, if they have clusters bound,  please update them to allow grace periods to unbind the existing openstack clusters. 
3. For deleted distributors, the process shall exit itself.
4. Build a distributor controller to start/update distributor processes.
5. The distributor controller watches crd objects and rebalances workload using consistent hashing.
6. Add unit tests for distributor
7. Add distributor controllers to start shell script

**Comment by jshaofuturewei** [comment]
The pull request #110  for distributor processes have been created. 
Reviewed the pull request #111  and found it is going to provide a separate id list. For pods to be partitioned, its uuid belongs to field selector like metadata.uuid which does not support set search conditions.

**Comment by cathyhongzhang** [comment]
will work on distributor controller logic.

**Comment by jshaofuturewei** [comment]
Added controller logic at #110 

Discussed the consistent hashing with Cathy yesterday and we would use the current implementation for the winter release.

**Comment by jshaofuturewei** [comment]
Updated #110 based on feedbacks
Added controller tests
For the distributor POD ID list, it is changed to distributor RANGE with [start, end) after discussion.

**Comment by cathyhongzhang** [comment]
distributor process coding and distributor controller coding are completed. Have updated the PR to include the updated codes. Have completed some unit test cases. Will design  more unit test cases and then upload the UT scripts to CI.

**Comment by cathyhongzhang** [comment]
completed
