### ISSUE TITLE
Test with cluster, scheduler, distributor, and dispatcher integrated together

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#121]
1. Make it sure the following components are ready to run
cluster, scheduler, distributor, and dispatcher 

2. Work out the test data for each component
CRD: cluster, scheduler, distributor, and  dispatcher
POD; new created pods, scheduler assigned pods, cluster bound pods, deleted pods

3. Create a controller manager to start the 4 CRD controllers

4. Update scripts to deploy a dev environment

5. Fix bugs if found.

**Comment by cathyhongzhang** [comment]
completed
