### ISSUE TITLE
POD status reset from "assigned"/"binded" to "running" after some time

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#138]
**What happened**:
The distributor will assign a POD to a selected scheduler by setting the POD status to "assigned" and the scheduler will bind the POD to a selected cluster by setting the POD status to "binded". But after some time, the POD status changes to "running", which is not the correct behavior.  
To avoid the problem, PR 134 removes the "startPodGCController" from the controller manager, which will impact the behavior of POD deletion.  

Need to investigate the right way to fix this.

**Comment by jshaofuturewei** [comment]
I might be related to my local controller managers. As I rollback to kube-controller-manager, it works fine now.  There is another issue that if a pod status phase is bound(binded, I correct its spelling) or assigned, the pods are thought as "terminated" and therefore get removed in the future. I fixed it in the PR #145

**Comment by jshaofuturewei** [comment]
ubuntu@ip-172-30-0-240:~/go/src/k8s.io/kubernetes$ cluster/kubectl.sh get pods
NAME    HASHKEY               READY   STATUS   RESTARTS   AGE
nginx   6090154181862305716   0/1     bound    0          54m
