### ISSUE TITLE
deleting the POD takes a long time

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#139]
**What happened**:
Deleting a POD takes a logn time.

**Comment by jshaofuturewei** [comment]
After applying kube-controller-manager, it does delete a pod in a short time.

**Comment by jshaofuturewei** [comment]
Ran 100 pod deletion and it took 0.12s to delete a pod on average.  Can't reproduce the bug.

**Comment by cathyhongzhang** [comment]
not an issue any more
