### ISSUE TITLE
check the mandatory flag for each POD field is properly set and also the API server should validate the mandatory fields.  

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#148]

**Comment by jshaofuturewei** [comment]
ResourceType: Required
ClusterName: Optional
VirtualMachine:
   NeedEIP: Optional
   Flavors: Required
      FlavorId: Optional
      Spot: Optional
        MaxPrice: Optional
        SpotDurationHours: Optional
        SpotDurationCount: Optional
        InterruptionPolicy: Optional
   ResourceCommonInfo:
     Count: Required
     Selector: Required
      GeoLocation: Optional
          City: Optional
          Province: Optional
          Area: Optional
          Country: Optional
  Regions: Optional
         Region: Required
         AvailablityZone: Optional
     Operator: Optional
     Strategy: Optional
        LocalStrategy: Optional

**Comment by cathyhongzhang** [comment]
will update the PR today
