### ISSUE TITLE
investigate why the sequence of cluster creation impact the dispatcher assignment and why some clusters have no dispatcher assigned

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#149]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by CoderKevinZhang** [comment]
This is not an issue with our codebase. When I am doing the test, everything works for me with no issues. After talking with Eunju, I found that the reason was Eunju checked out the result too fast which means the process has not been finished yet.
