### ISSUE TITLE
Performance of associating schedulers and clutsers

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#166]
It takes 30~40 minutes to associate clusters and schedulers when the number of clusters are 1000.
Steps:
(1) ./hack/globalscheduler/start_mock_scheduler.sh
(2) kubectl apply -f test_schedulers.yaml 
(3) kubectl apply -f 1000clusters.yaml 
(4) kubectl get clusters -o wide

**Comment by CoderKevinZhang** [comment]
I0123 01:22:57.749241   12337 cluster_controller.go:126] Enqueue Create cluster -default/cluster0
...
I0123 01:29:35.468905   12337 scheduler_controller.go:217] [ Scheduler Controller ]Successfully synced 'default/cluster999'

**Comment by CoderKevinZhang** [comment]
As per the log, it took about 6~7min to associate 1000 clusters with 4 schedulers when union functionality is working ideally
