### ISSUE TITLE
Script to create 1000 cluster data with a variety of specifications

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#168]
This script will create clusters' yaml file according to required parameters such as the number of clusters, locations, flavors, and storages.
For example, 1000 clusters with a variety of 
10 locations (regions) - East-1, East-2, West-1, West-2, South-1, South-2, North-1, North-2, Central-1, Central-2
7 combinations of flavors - (small, medium, large)
7 combinations of flavors - (sata, sas, ssd)

**Comment by cathyhongzhang** [comment]
will upload the PR
