### ISSUE TITLE
Scheduler Controller and Dispatcher Controller: Update event compete when cluster create

### ISSUE THREAD

**Issue by CoderKevinZhang** [futurewei-cloud/global-resource-scheduler#172]
**Which jobs are failing**:
End to end pod creation

**Which test(s) are failing**:
cluster instance creation is failing

**Since when has it been failing**:
when creating dispatcher instance first

**Reason for failure**:
when creating a dispatcher instance, it didn't get the latest resource version of the cluster instance to do the update since the scheduler controller also needs to do the update for the cluster at the same time. So scheduler controller and dispatcher controller are competing to do the update.

**Anything else we need to know**:
Test Steps:
1: ./hack/globalscheduler/globalscheduler-up.sh
 
2: ./hack/globalscheduler/start_mock_scheduler.sh

3: kubectl apply -f globalscheduler/test/yaml/sample_dispatcher.yaml
 
4: kubectl apply -f globalscheduler/test/mock/cluster.yaml

Error image:
![image](https://user-images.githubusercontent.com/19650434/105543929-3b5e4c80-5caf-11eb-859d-3d5dbeb92b91.png)

**Comment by cathyhongzhang** [comment]
Kevin will verify this issue after the resoruce version issue is fixed.

**Comment by CoderKevinZhang** [comment]
Issue has been fixed
