### ISSUE TITLE
Failed to register 1000 clusters in schedulers

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#175]
Run the following steps
1.  ./hack/globalscheduler/globalscheduler-up.sh
2.  ./hack/globalscheduler/start_mock_scheduler.sh
3.  ./hack/globalscheduler/test/create_pods.sh 1000
4. cluster/kubectl.sh apply -f globalscheduler/test/mock/distributors.yaml
5. ./hack/globalscheduler/test/create_clusters.sh 1000

Please check global-resource-scheduler.log and found the following errors

![image](https://user-images.githubusercontent.com/50841010/105738099-895f9400-5eeb-11eb-9511-6988138b2b12.png)

And run cluster/kubectl.sh get scheduler -o json and found there are only 13 clusters and all the storage capacities are separated
![image](https://user-images.githubusercontent.com/50841010/105738276-b57b1500-5eeb-11eb-9d38-acc6b2add153.png)

![image](https://user-images.githubusercontent.com/50841010/105738819-4fdb5880-5eec-11eb-8d9c-d8bd3ac66506.png)

**Comment by CoderKevinZhang** [comment]
Issue has been fixed
