### ISSUE TITLE
Dispatchers failed to update their cluster ranges after creating 1000 clusters

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#176]
Run the following steps

1 ./hack/globalscheduler/globalscheduler-up.sh
2 ./hack/globalscheduler/start_mock_scheduler.sh
3 ./hack/globalscheduler/test/create_pods.sh 1000
4 cluster/kubectl.sh apply -f globalscheduler/test/mock/distributors.yaml
5 ./hack/globalscheduler/test/create_clusters.sh 1000
6 cluster/kubectl.sh apply -f globalscheduler/test/mock/dispatchers.yaml

Ran the following command cluster/kubectl.sh get dispatchers to get the result as attached.
![image](https://user-images.githubusercontent.com/50841010/105739298-d42ddb80-5eec-11eb-908f-e2e85ce0bee6.png)

And check global-resource-scheduler.log and found the following errors
![image](https://user-images.githubusercontent.com/50841010/105739764-4ef6f680-5eed-11eb-83f5-d6fb97ec1405.png)

**Comment by cathyhongzhang** [comment]
The root cause issue may be related to issue #175

**Comment by jshaofuturewei** [comment]
The issue has been fixed
