### ISSUE TITLE
global scheduler terminated unexpectedly

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#177]
Global scheduler 
Steps:

./hack/globalscheduler/globalscheduler-up.sh       
./hack/globalscheduler/start_mock_scheduler.sh       
hack/globalscheduler/test/create_pods.sh   
hack/globalscheduler/test/create_clusters.sh 10   
kubectl apply   -f sample_distributor.yaml  
kubectl apply   -f sample_dispatcher.yaml
kubectl get   distributor   
kubectl get   scheduler   
kubectl get   dispatcher   
kubectl get   cluster

![image](https://user-images.githubusercontent.com/59618483/105751803-5cb37880-5efb-11eb-8a8f-d7d57bad65f0.png)

![image](https://user-images.githubusercontent.com/59618483/105751831-63da8680-5efb-11eb-9b0b-50799eb2374c.png)

![image](https://user-images.githubusercontent.com/59618483/105934328-d5eac280-6004-11eb-9550-be402f0050cb.png)

**Comment by jshaofuturewei** [comment]
It looks like a kernel issue from the error message given

**Comment by CoderKevinZhang** [comment]
> It looks like a kernel issue from the error message given

Did you go /tmp folder to check what happened in the log?

**Comment by cathyhongzhang** [comment]
Eunju will test it again to see if it is still there
