### ISSUE TITLE
scheduler controller sets the assoication of clusters to schedulers based on geolocation

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#182]
Here is the code logic that should be implemented: 
Scheduler controller will set the assoication of clusters to schedulers based on cluster's geolocation.
1. if the number of unique countries of all clusters > the number of schedulers, divide the clusters evenly among the schedulers based on cluster country, i.e. clusters belonging to the same country will be assigned to the same scheduler, but not vice verse
2. else if the number of unique areas of all clusters > the number of schedulers, divide the clusters evenly among the schedulers based on cluster area, i.e. clusters belonging to the same area (of course, they will also belong to the same country) will be assigned to the same scheduler, but not vice verse
3. else if the number of unique provinces of all clusters > the number of schedulers, divide the clusters evenly among the schedulers based on cluster provice, i.e. clusters belonging to the same province (of course, they will also belong to the same country and same area) will be assigned to the same scheduler, but not vice verse
4. else if the number of unique cities of all clusters > the number of schedulers, divide the clusters evenly among the schedulers based on cluster city, i.e. clusters belonging to the same city (of course, they will also belong to the same country, same area, and same province) will be assigned to the same scheduler, but not vice verse

**Comment by CoderKevinZhang** [comment]
Codes logic has been implemented
