### ISSUE TITLE
global resource scheduler terminated unexpectedly

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#187]
**What happened**: 
global resource scheduler terminated unexpectedly

![image](https://user-images.githubusercontent.com/59618483/106071870-ee69e400-60bb-11eb-9b61-303b85e3760d.png)

**What you expected to happen**: 
global resource scheduler should continuously run until admin stop it

**How to reproduce it (as minimally and precisely as possible)**:
1. ./hack/globalscheduler/globalscheduler-up.sh
2. ./hack/globalscheduler/test/create_clusters.sh 2
3. kubectl apply -f globalscheduler/test/mock/mock_scheduler.yaml
4. kubectl apply -f globalscheduler/test/mock/distributors.yaml
5. kubectl apply -f globalscheduler/test/mock/dispatchers.yaml
6. kubectl describe cluster cluster-0
7. kubectl describe cluster cluster-1

**Anything else we need to know?**:
/tmp/global-resource-scheduler.log

![image](https://user-images.githubusercontent.com/59618483/106072135-78b24800-60bc-11eb-8ce2-dc9a973a4fcf.png)

**Environment**:
- Arktos version (use `kubectl version`): 
-Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-752+e813c97640194c-dirty", GitCommit:"e813c97640194c8b7cf0cac8ef480481cdf0615a", GitTreeState:"dirty", BuildDate:"2021-01-28T00:08:58Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu18
- Kernel (e.g. `uname -a`): 
- Linux ip-172-31-19-112 4.4.0-1119-aws #133-Ubuntu SMP Tue Dec 1 19:04:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jshaofuturewei** [comment]
It is fixed in https://github.com/futurewei-cloud/global-resource-scheduler/pull/186

**Comment by kimeunju108** [comment]
This error didn't happen for another testing. If it happen again, eunju will open this issue again. Now this issue will be closed.
