### ISSUE TITLE
Pod request is not scheduled & sent to openstack when geolocation data is not null

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#188]
**What happened**:
Pod creation request is not scheduled and wasn't sent to openstack if geolocation is data is not ""

**What you expected to happen**:
VM pod should be created in both global scheduler and openstack
**How to reproduce it (as minimally and precisely as possible)**:
1. ./hack/globalscheduler/globalscheduler-up.sh
2. ./hack/globalscheduler/test/create_clusters.sh 2
3. kubectl apply -f globalscheduler/test/mock/mock_scheduler.yaml
4. kubectl apply -f globalscheduler/test/mock/distributors.yaml
5. kubectl apply -f globalscheduler/test/mock/dispatchers.yaml
6. kubectl apply -f pod1.yaml 

pod1.yaml (not working)
`apiVersion: v1
kind: Pod
metadata:
  name: "pod-test-1"
spec:
  resourceType: "vm"
  virtualMachine:
    name: "openstack-test-1"
    image: "9e2b5eb9-3bb0-469b-b901-a75d87e4d958"
    securityGroupId: "5e9513a8-b779-4cb9-825b-a1e994f28ddc"
    keyPairName: "demo-keypair"
    flavors:
    - flavorID: "42"
    resourceCommonInfo:
      count: 1
      selector:
        geoLocation:
          city: "Renton"
          country: "USA"
          province: "Washington"
        regions:
         - region: "NW"     
  nics:
    - name: "c32fa6da-ee3f-4c65-80a7-c920c0a9ce7e"
 '

pod1.yaml (working)
`apiVersion: v1
kind: Pod
metadata:
  name: "pod-test-1"
spec:
  resourceType: "vm"
  virtualMachine:
    name: "openstack-test-1"
    image: "9e2b5eb9-3bb0-469b-b901-a75d87e4d958"
    securityGroupId: "5e9513a8-b779-4cb9-825b-a1e994f28ddc"
    keyPairName: "demo-keypair"
    flavors:
    - flavorID: "42"
    resourceCommonInfo:
      count: 1
      selector:
        geoLocation:
          city: " "
          country: " "
          province: " "
        regions:
         - region: "NW"     
  nics:
    - name: "c32fa6da-ee3f-4c65-80a7-c920c0a9ce7e"
 '

**Anything else we need to know?**:
screen capture:
![image](https://user-images.githubusercontent.com/59618483/106074772-4e16be00-60c1-11eb-96b0-5ba5f5845436.png)

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kimeunju108** [comment]
Pod data format is changed. Eunju will apply to all sample pod data

**Comment by cathyhongzhang** [comment]
not an issue any more
