### ISSUE TITLE
Modified VM POD creation/deletion API (add new fields required by the Nano Resource Allocation API)---Modify VM POD resource Template

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#20]

**Comment by jshaofuturewei** [comment]
PodSpec
      - ResourceType: VM/Container
      - Containers: [
             {
                 - Name: Container1 
                 - Storage: {
                     - Type: SATA
                     - Volume: 40
                }
                - Selector: {
                     - GeoLocation: {
                          - City:
                          - Province:
                          - Area:
                          - Country: 
                     }
                     - Regions: {
                          - Name:
                          - AvailablityZone: [
                                "Zone1",
                                "Zone2",
                         ]
                     }
                     - Operator:
                     - Strategy:
                }
                - Count: 1
             }
      ]
      - VirtualMachines: [
            {
                - Name: VM1 
                - Need_EIP: true
                - FlavorId: {
                   - FlavorId: t6.large.2
                  - Spot: {
                        - MaxPrice: 1.5
                        - SpotDurationHours: 1
                        - SpotDuractionCount: 2
                        - InterruptionPolicy: immedate
                     }
                }
                - Storage: {
                     - Type: SSD
                     - Volume: 40
                }
                - Selector: {
                     - GeoLocation: {
                          - City:
                          - Province:
                          - Area:
                          - Country: 
                     }
                     - Regions: {
                          - Name:
                          - AvailablityZone: [
                                "Zone1",
                                "Zone2",
                         ]
                     }
                     - Operator:
                     - Strategy:
                }
                - Count: 1
            }
      ]
