### ISSUE TITLE
2 dispatcher have same cluster ranges 

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#203]
Among 10 clusters, both dispatcher1 and dispatcher2 have range cluster0~ cluster4. No dispatcher is associated to cluster5 ~ cluster9.
<Steps>
1. ./hack/globalscheduler/globalscheduler-up.sh
2. kubectl apply -f sample_10_clusters.yaml
3. kubectl apply -f mock_scheduler.yaml
4. kubectl apply -f sample_2_distributors.yaml
5. kubectl apply -f sample_2_dispatchers.yaml
6. ./hack/globalscheduler/test/create_pods.sh 10 0.01

![image](https://user-images.githubusercontent.com/59618483/107018825-c6cae980-6755-11eb-9bf0-50c9937bd323.png)

**Comment by jshaofuturewei** [comment]
I can't reproduce it using the same steps. Please provide detailed logs
![image](https://user-images.githubusercontent.com/50841010/107022043-c2a0cb00-6759-11eb-830c-6aae7b6cb409.png)
