### ISSUE TITLE
Only one mock scheduler created 

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#207]
It created only one mock scheduler (name: mockscheduler1) even if yaml files includes 2 mock schedulers

- 1000 clusters, 100 pods, 2 mock schedulers, 2 distributors, and 2 dispatchers
- 100 pods were scheduled well 
- Average latency: 11.29 milliseconds/pod

![image](https://user-images.githubusercontent.com/59618483/107295445-3d9d0680-6a24-11eb-87e8-b0c7a76aa703.png)
[Figure 1] It shows all pods were associated only with mock scheduler1

Test steps:
1. ./hack/globalscheduler/globalscheduler-up.sh
2. kubectl apply -f sample_1000_clusters.yaml
3. kubectl apply -f sample_2_mockschedulers.yaml  (5 min)
4. kubectl apply -f sample_2_distributors.yaml   
5. kubectl apply -f sample_2_dispatchers.yaml
6. ./hack/globalscheduler/test/create_pods.sh 100 0.01

Log files:
[1000 custers, 100 pods Log files] (https://github.com/kimeunju108/global-resource-scheduler/tree/testlogs/globalscheduler/test/testlogs/test1-1000clusters-100pods)

**Comment by jshaofuturewei** [comment]
Thanks for the detailed information. Since the 2 schedulers have already in etcd, could you please provide me the gs-controllers log?

**Comment by jshaofuturewei** [comment]
I can't reproduce the issue. However, the previous scheduler controller does have issues with distributing clusters. Please verify if you have the same issue with the latest PR.
