### ISSUE TITLE
balanceScheduler function failed

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#208]
There is the following error in scheduler_controller at gs-controllers.ERROR
E0208 18:19:32.105329    5111 scheduler_controller.go:227] error syncing 'default/mockscheduler2': balanceScheduler function failed
- 20 clusters, 100 pods, 2 mock schedulers, 2 distributors, and 2 dispatchers
- many pods were scheduled well, but some of them are not scheduled

Testing steps:
./hack/globalscheduler/globalscheduler-up.sh
kubectl apply -f sample_20_clusters.yaml
kubectl apply -f sample_2_mockschedulers.yaml  (5 min)
kubectl apply -f sample_2_distributors.yaml   
kubectl apply -f sample_2_dispatchers.yaml
./hack/globalscheduler/test/create_pods.sh 100 0.01

Log files:
20 cluster, 100 pods Log files [https://github.com/kimeunju108/global-resource-scheduler/blob/testlogs/globalscheduler/test/testlogs/test6-20clusters-100pods/gs-controllers.ip-172-31-19-112.root.log.ERROR.20210208-181140.5111](https://github.com/kimeunju108/global-resource-scheduler/blob/testlogs/globalscheduler/test/testlogs/test6-20clusters-100pods/gs-controllers.ip-172-31-19-112.root.log.ERROR.20210208-181140.5111)

**Comment by jshaofuturewei** [comment]
Please verify the PR to see if it fixes the issue. Thanks
