### ISSUE TITLE
Error - register cluster crd : CRD is not accepted

### ISSUE THREAD

**Issue by CoderKevinZhang** [futurewei-cloud/global-resource-scheduler#218]
**What happened**:
![image](https://user-images.githubusercontent.com/19650434/108142656-0b6e5300-707b-11eb-9c7b-361be6c9b4a0.png)

**What you expected to happen**:
No error should occur

**How to reproduce it (as minimally and precisely as possible)**:
A random issue that could happen after running the command: ./hack/globalscheduler/globalscheduler-up.sh

**Comment by jshaofuturewei** [comment]
Based on the error thrown, it happens before creating cluster crds or after creating crds to verify if the cluster crd exists. https://github.com/futurewei-cloud/global-resource-scheduler/blob/master/globalscheduler/controllers/cluster/cluster_crd.go#L47

There is a bug to check if the cluster crd exists in the https://github.com/futurewei-cloud/global-resource-scheduler/blob/master/globalscheduler/controllers/cluster/cluster_crd.go#L40

Check the following screenshot that the crd actual condition status can be either NameAccepted or Established. It might take a while to get to the Established status.
![image](https://user-images.githubusercontent.com/50841010/108233018-377be980-70f8-11eb-9124-33b54a862fb8.png)
