### ISSUE TITLE
All the pods are processed by dispatcher2 only

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#221]
Repo steps
1. kubectl apply -f globalscheduler/test/yaml/sample_1000_clusters.yaml
2. kubectl apply -f globalscheduler/test/yaml/sample_1000_mockschedulers.yaml
3. kubectl apply -f globalscheduler/test/yaml/sample_2_distributors.yaml
4. kubectl apply -f globalscheduler/test/yaml/sample_2_dispatchers.yaml
5. hack/globalscheduler/test/create_pods.sh 100 0.01

All the pods are sent to openstack via dispatcher2
![image](https://user-images.githubusercontent.com/50841010/108459496-a148e000-722b-11eb-94dd-4afbe429420e.png)

**Comment by jshaofuturewei** [comment]
It is related to the hq scheduler cache mechanisms, always picking up the top clusters from stacks. as Kevin mentioned. HQ team will fix it.

**Comment by jshaofuturewei** [comment]
Based on the resource collector logs, the resource collector just created site info based on the last 10 clusters. I attached the log below for reference.
![image](https://user-images.githubusercontent.com/50841010/108783679-be7af880-7522-11eb-9561-55c85d18589b.png)

**Comment by cathyhongzhang** [comment]
This is not a real bug. The issue is caused by our simulation of fake clusters which share the same region+AZ
