### ISSUE TITLE
The current openstack can only handle 10 m1.nano(flavor 42) vms not 100 as expected

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#222]
Repo steps

kubectl apply -f globalscheduler/test/yaml/sample_1000_clusters.yaml
kubectl apply -f globalscheduler/test/yaml/sample_1000_mockschedulers.yaml
kubectl apply -f globalscheduler/test/yaml/sample_2_distributors.yaml
kubectl apply -f globalscheduler/test/yaml/sample_2_dispatchers.yaml
hack/globalscheduler/test/create_pods.sh 100 0.01

Only 10 vms have been created at the openstack. The rest failed due to reaching capacity.

![image](https://user-images.githubusercontent.com/50841010/108459742-203e1880-722c-11eb-94b3-7a2385b6fa04.png)

**Comment by jshaofuturewei** [comment]
The configuration is set to avoid openstack crash as expected.

**Comment by CoderKevinZhang** [comment]
Have already set the limits of openstack to handle 100 pods right now
