### ISSUE TITLE
Set up availability zones for openstack hosts

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#228]
Based on the reference at https://docs.openstack.org/nova/latest/admin/availability-zones.html, we could assign availability zones  to openstack hosts. The information is missing during the tests. Wondering if we could add fake availability zones to the created host and test if we can get them when listing site resources.

According to the codes https://github.com/futurewei-cloud/global-resource-scheduler/blob/master/staging/src/k8s.io/cloud-provider/cloud.go#L214, it looks like we can get zone information if openstack supports it.

**Comment by cathyhongzhang** [comment]
completed
