### ISSUE TITLE
Cluster CRD creation(registration)/deletion---API Implementation

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#23]
**What would you like to be added**:

**Why is this needed**:

**Comment by cathyhongzhang** [comment]
This includes saving the object in ETCD

**Comment by nkwangjun** [comment]
Is there any api docs?

**Comment by kimeunju108** [comment]
Hello,

We have some API design documents for the issue 23 in the following address:
https://github.com/futurewei-cloud/global-resource-scheduler/blob/master/docs/design-proposals/global-scheduler
Please feel free to tell me if you have a question.

Best,

Eunju Kim

**Comment by yxiong2020** [comment]
35% completed on this item.

**Comment by yxiong2020** [comment]
50% done on this item

**Comment by kimeunju108** [comment]
60% completed on this item.

**Comment by kimeunju108** [comment]
70%  completed on this item. CICD testing are remained.

**Comment by kimeunju108** [comment]
80% completed on this item.

**Comment by cathyhongzhang** [comment]
PR already created.
