### ISSUE TITLE
Investigate whether existing resource collector code or scheduler code constructs available flavor resource from available cpu, memory etc. 

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#238]
**What would you like to be added**:

**Why is this needed**:

**Comment by jshaofuturewei** [comment]
Flavor information are static based at resource collectors. Please refer to globalscheduler/pkg/scheduler/client/informers/flavor/flavor.go.  It will list flavor type definitions, such as m1.tiny.

In Scheduler, it does some flavor calculation at globalscheduler/pkg/scheduler/sitecacheinfo/sitecache_info.go
such as 	count := (totalRes.VCPU - requestRes.VCPU) / vCPUInt
		memCount := (totalRes.Memory - requestRes.Memory) / flv.Ram

**Comment by cathyhongzhang** [comment]
completed
