### ISSUE TITLE
Missing site cache in scheduler even after it received resource information through UpdateSiteDynamicResource

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#257]
1.  cluster/kubectl.sh apply -f globalscheduler/test/yaml/sample_2_schedulers.yaml
2. Updated hack/globalscheduler/test/create_clusters.sh using new ip 34.220.41.107 and az "non-production-az" in this openstack cluster. Updated its region to be the same as the one hack/globalscheduler/test/create_pods.sh
3.  hack/globalscheduler/test/create_clusters.sh 20
4. cluster/kubectl.sh apply -f globalscheduler/test/yaml/sample_2_distributors.yaml
5. hack/globalscheduler/test/create_pods.sh 20 0.1

Please review the attached log. The region is "Central-2" and the site info is created through UpdateSiteDynamicResource. However, when a pod with the same az and geoLocation tried to check if the site is available, it got nil cache and threw exception

![image](https://user-images.githubusercontent.com/50841010/113180938-2699ba00-9206-11eb-9012-516385af5200.png)

**Comment by kimeunju108** [comment]
This is fixed and will make a new PR soon

**Comment by cathyhongzhang** [comment]
will upload PR today
