### ISSUE TITLE
Scheduler CRD creation/deletion --- implement the controller logic

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#33]
**What would you like to be added**:

**Why is this needed**:

**Comment by yxiong2020** [comment]
Logic
1. Watch new schedulers and watch new clusters
2. Determine (scheduler partitioning algorithm)  home schedulers for new clusters  - first release based on average
3. Start new instance of scheduler and inform distributor of new schedule instances
4. Watch any update/deletion of existing schedulers, existing clusters and take proper actions（？)

**Comment by yxiong2020** [comment]
25% completed on this item

**Comment by yxiong2020** [comment]
30% 
1. Completed scheduler startup process

**Comment by cathyhongzhang** [comment]
PR for scheduler start script created. 
33% controller logic done.

**Comment by CoderKevinZhang** [comment]
Individual scheduler processes starting tests have done.
35% controller logic done.

Next: working on making sure that the selected scheduler can get the Pod requested.

**Comment by cathyhongzhang** [comment]
1. working on the logic to watch the binding of POD to scheduler by the distributor. 
2. scheduler creation/deletion logic is done
3. cluster registration/unregistration logic not done yet.

**Comment by CoderKevinZhang** [comment]
Logic of watching the binding of POD to the scheduler by the distributor is finished 80%. Failed the CI test, working on fixing it.

**Comment by CoderKevinZhang** [comment]
- [ ] 1. working on the logic to watch the binding of POD to the scheduler by the distributor.
- [ ] 2. scheduler creation/deletion logic is done
- [ ] 3. cluster registration/unregistration logic not done yet.

**Comment by cathyhongzhang** [comment]
working on the watching of cluster object and add the logic

**Comment by CoderKevinZhang** [comment]
[ Done ] Watching of cluster object and add the logic

[ Pending ] Testing cluster object watching under globalschduler-controller-manager

[ Discussing ] Globalscheduler starting script / whether using CRD for scheduler

**Comment by CoderKevinZhang** [comment]
Working on consistent hashing. 60% of the work has been finished.

Performance test and change cluster -> scheduler binding logic still remain.

**Comment by CoderKevinZhang** [comment]
Consistent Hashing DONE!

Performance Test DONE!

Change cluster -> scheduler binding logic REMAIN.

**Comment by CoderKevinZhang** [comment]
Update:
10 schedulers / 10,000 clusters performance -- 131,072 virtual nodes has the best performance.

working on the scheduler controller logic update.

will make a PR today about the consistent hashing implementation

**Comment by cathyhongzhang** [comment]
1. consistent hashing PR will be created today.
2. scheudler controller logic 30% done

**Comment by cathyhongzhang** [comment]
scheduler controller logic: 30% done, working on unuion of clusters' resoruce profile

**Comment by cathyhongzhang** [comment]
scheudler controller logic: 60% completion. union of clusters' resoruce profile will be done by today.

**Comment by cathyhongzhang** [comment]
1. scheudler controller logic and scheduler process logic: 100%, will upload the PR today
2. start working on testing scripts for inclusion into CI
3. will create a PR for updating the consistent hashing function which will returns the ID list

**Comment by cathyhongzhang** [comment]
1. scheduler process logic PR done
2. consistent hashing PR done
3. scheduler controller logic PR will be updated when UT is done. Planned to be done by next Monday
4. working on UT for 1, 2, 3 and include them in CI

**Comment by cathyhongzhang** [comment]
completed
