### ISSUE TITLE
remove kubelet

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#37]
**What would you like to be added**:

**Why is this needed**:

**Comment by CoderKevinZhang** [comment]
Removing kubelet would infect the current scheduler functionality, thus close this issue for now. Will come back when HQ submit their version of the scheduler function.

**Comment by CoderKevinZhang** [comment]
Removing kubelet would infect the current scheduler functionality, thus close this issue for now. Will come back when HQ submit their version of the scheduler function.
