### ISSUE TITLE
POD Request Distributor/Controller ---implement the controller logic

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#39]
**What would you like to be added**:

**Why is this needed**:

**Comment by cathyhongzhang** [comment]
This should include implementing local cache for low-latency query of the scheduler partition info

**Comment by yxiong2020** [comment]
Need to document design of controller logic (dispatch logic or algorithm) - for now, rand robin a list of scheduler instances

**Comment by yxiong2020** [comment]
30% completed on this item.

**Comment by jshaofuturewei** [comment]
50% completed.
1. Completed its diagram
2. Created a command to start it.
3. Working on the informers to sync data and clientset to assign schedulers to pods

**Comment by jshaofuturewei** [comment]
70% completed.
1. Completed informers
2. Completed clienttset
3. Working on tests

**Comment by cathyhongzhang** [comment]
Based on our discussion, Jun will add profile matching logic to selection of a scheduler to bind the POD. So the work completion is changed to 60%

**Comment by cathyhongzhang** [comment]
Jun will update the distributor logic diagram based on today's discussion

**Comment by cathyhongzhang** [comment]
70% completed

**Comment by jshaofuturewei** [comment]
75% completed
1. Added new type distributor
2. Added new roles for distributor in bootstrap

**Comment by cathyhongzhang** [comment]
dispatcher controller logic coding is completed. But will use the correct controller code generator to generate the correct controller code base and port over the controller logic codes to this new code base. UT test cases are already completed. need to think about integration test cases. UT scripts and IT scripts will be merged in separate PR.

**Comment by jshaofuturewei** [comment]
80% completed
1. Ran code generator successfully
2. Added unit tests
3. Added assigned scheduler tag to pod as Kevin requested
4. Working on Integration tests

**Comment by cathyhongzhang** [comment]
IT is done. 
work on merging with Kevin and Eujun's change

**Comment by jshaofuturewei** [comment]
Updated based on the allocation request body at https://github.com/futurewei-cloud/global-resource-scheduler/pull/81

**Comment by cathyhongzhang** [comment]
Jun will create an issue to modify (hardcode)  existing k8s scheduler or the new lightweight scheudler to connect Jun's dispatcher code and Kevin's scheduler code for integration testing purpose.

**Comment by cathyhongzhang** [comment]
already integrated with Kevin's code. But CI/CD is failing. WIll run CI/CD again.

**Comment by jshaofuturewei** [comment]
The pull request has been approved. Ran another test with the latest code merged and will merge it if it passes CI/CD
