### ISSUE TITLE
replace existing K8S Scheduler with the new light-weight scheduler and add informer interface with API server

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#42]
1. The new Scheduler should be able to watch "binding/unbinding of a POD object to this scheduler" event from the API server
2. Whenever the event happens, it will run scheduling algorithm to schedule the POD
3. It can query cluster resource info in its local cache, but it should also be able to access static cluster information, such as cluster geolocation, region, operator, flavor type IDs, storage type, price, etc. in ETCD. 
4. It should send POD request to the openstack cluster for cluster-level scheduling via openstack VM creation/deletion API

**Comment by nkwangjun** [comment]
assign to me please

**Comment by nkwangjun** [comment]
assign to me please

**Comment by nkwangjun** [comment]
implemented in # 146

**Comment by cathyhongzhang** [comment]
completed
