### ISSUE TITLE
cluster resource collector---API implementation and resource saving into cache

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#44]
1. implement a generic pull API for collecting each cluster's resource 
2. save the cluster resource info into the cache of every scheduler instance (there will be multiple scheduler instance with each one responsible for a partition), alternatively you can save it to a DB and sync up each scheduler's cache to the DB. 
3. The resource object data structure should easily be extended (key-value map) to hold more info in the future

**Comment by nkwangjun** [comment]
assign to me?

**Comment by cathyhongzhang** [comment]
completed
