### ISSUE TITLE
The scheduleing platform should send POD request to the openstack cluster for cluster-level scheduling via openstack VM creation/deletion API

### ISSUE THREAD

**Issue by nkwangjun** [futurewei-cloud/global-resource-scheduler#62]
There should be a "openstack adapter" for the scheduler to do the request send, and it can be called in the "binder plugins"

**Comment by cathyhongzhang** [comment]
there are two ways to do this:
1. The scheduler adds the binding of the POD to the selected cluster in ETCD. Another Dispatcher process watches this binding throguh API server and send this POD request to the selected Openstack cluster. 
2. The scheduler places the scheduling result into a queue or channel. Another separate thread in the scheduler process dequeues the scheduling result and sends the POD request to the selected Openstack cluster.

**Comment by cathyhongzhang** [comment]
open two new PRs (82 and 83) to replace this one.
