### ISSUE TITLE
Design/Implement API/Interfaces from Cluster Controller to Resource Collector for registering a new cluster and de-registering a existing cluster.

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#74]
**What would you like to be added**:
API for handling requests from cluster controller to resource collector, and corresponding responses from resource collector  

**Why is this needed**:
When a cluster is registered/unregistered, the ClusterController should relay/remove the cluster's registration information, such as the cluster's geolocation, to/from the resource collector through this API. The Resource Collector, which implements this API, will save/remove the cluster's static infromation in its local cache so that the scheduling algorithm can use this info.

**Comment by cathyhongzhang** [comment]
This issue is tracked by issue #27
