### ISSUE TITLE
Design/Implement API/Interface from Resource Collector to Cluster Controller for updating cluster status (good or bad)

### ISSUE THREAD

**Issue by kimeunju108** [futurewei-cloud/global-resource-scheduler#75]
**What would you like to be added**:
Cluster update APIs for ResourceCollector

**Why is this needed**:
When there is a change in a cluster status (e.g., crash), ResourceCollector will detect the change. Then ResourceCollector will pass the cluster's status to Cluster Controller. The Cluster Controller should update the cluster object in the ETCD with the latest cluster status. If the status is "down" or "unreachable" (this depends on how we define the status enum values), the cluster controller should detach the association of the cluster with its scheduler (i.e., remove the cluster from the scheduler's partition pool) so that the scheduler will not schedule any POD to this cluster. Note that registration and unregistration of a cluster will only come from one entry, i.e. through the API server by an admin.

**Comment by cathyhongzhang** [comment]
need to decide on the communication interface protocol, gRPC and HTTP2. Let's discuss this in today's open source meeting.

**Comment by cathyhongzhang** [comment]
This issue is tracked by issue #27
