### ISSUE TITLE
Modify scheduler to accept pods with scheduler assigned to bind clusters for integration testing purpose

### ISSUE THREAD

**Issue by jshaofuturewei** [futurewei-cloud/global-resource-scheduler#93]
The current lightweight scheduler  https://github.com/futurewei-cloud/global-resource-scheduler/pull/81 accepts allocation and assign nodes to the allocations, which can not connect to our scheduler CRD and distributors now.

For integration tests, the following modification might be made
1. Watch pods with scheduler CRD assigned
2. Watch clusters for capacity information
3. Based on the scheduler CRD and cluster information, bind available clusters to pods and update their status

**Comment by cathyhongzhang** [comment]
1. simplified informer code to watch the binding of the POD to the scheduler in ETCD, which is done by the distributor
2. Once getting the POD, use round robin way to select a cluster from the scheduler's associated cluster partition/group to host that POD, update the ETCD with the binding of the POD to the cluster. 

All these codes are for integration testing purpose for the time being.

**Comment by jshaofuturewei** [comment]
50% completed.

**Comment by cathyhongzhang** [comment]
PR created. need to fix the CI/CD test failures

**Comment by CoderKevinZhang** [comment]
CI/CD tests have all passed. Will run the integration today. Once passed, will provide the code frame to get the performance.

**Comment by cathyhongzhang** [comment]
Will measure the performance 👍 
1. successful rate of incoming PODs binding to scheduler
2. maximum QPS handled by distributor

**Comment by jshaofuturewei** [comment]
Tried to integrate the current components together

1. Cluster controller started successfully
2. Scheduler is still under development. 
3. Missing gs-scheduler.sh from the #101 and #104 to start
4. Added scheduler and cluster types in binding target as discussed. #106
